# Generated by Django 5.1.6 on 2025-06-28 22:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inv', '0006_producto_foto'),
    ]

    operations = [
        migrations.AddField(
            model_name='producto',
            name='tipo_producto',
            field=models.CharField(choices=[('P', 'Perecedero'), ('NP', 'No Perecedero')], default='NP', max_length=2, verbose_name='Tipo de Producto'),
        ),
    ]
